-- TEMPORARY diagnostic. Remove once canonical ACL mismatch is identified.
begin;
select no_plan();

create temporary table expected_acl (
  signature text primary key,
  anon_allowed boolean not null,
  authenticated_allowed boolean not null,
  service_role_allowed boolean not null
);

insert into expected_acl values
  ('public.is_active_user()', false, true, true),
  ('public.current_crm_role()', false, true, true),
  ('public.is_owner()', false, true, true),
  ('public.can_manage_crm()', false, true, true),
  ('public.can_access_client(uuid)', false, true, true),
  ('public.can_manage_client(uuid)', false, true, true),
  ('public.crm_storage_object_is_known(text)', false, true, true),
  ('public.crm_storage_object_readable(text)', false, true, true),
  ('public.crm_storage_object_writable(text)', false, true, true),
  ('public.can_access_artist(uuid)', false, true, true),
  ('public.can_manage_artist(uuid)', false, true, true),
  ('public.can_view_artist_finance(uuid)', false, true, true),
  ('public.can_manage_artist_finance(uuid)', false, true, true),
  ('public.can_manage_artist_sessions(uuid)', false, true, true),
  ('public.can_manage_artist_integrations(uuid)', false, true, true),
  ('public.create_enquiry_intake(uuid,jsonb,jsonb,jsonb)', false, false, true),
  ('public.create_trusted_enquiry_intake(text,text,text,uuid,jsonb,jsonb,jsonb)', false, false, true),
  ('public.mark_enquiry_file_uploaded(uuid,text)', false, false, true),
  ('public.finalize_enquiry_intake(uuid)', false, false, true),
  ('public.fail_enquiry_intake(uuid,text)', false, false, true),
  ('public.record_outbox_attempt(uuid,boolean,text)', false, false, true),
  ('public.record_whatsapp_inbound_message(uuid,text,text,text,timestamptz,text,text)', false, false, true),
  ('public.record_whatsapp_message_status(uuid,text,text,text,timestamptz)', false, false, true),
  ('public.claim_whatsapp_outbox(text,integer,integer)', false, false, true),
  ('public.claim_whatsapp_outbox_by_id(uuid,text,integer)', false, false, true),
  ('public.record_whatsapp_outbox_result(uuid,text,boolean,text,text)', false, false, true),
  ('public.claim_telegram_outbox(text,integer,integer)', false, false, true),
  ('public.claim_telegram_outbox_by_id(uuid,text,integer)', false, false, true),
  ('public.record_telegram_outbox_result(uuid,text,boolean,text)', false, false, true),
  ('public.resolve_outbox_route(uuid)', false, false, true),
  ('public.list_incomplete_intakes(integer,integer)', false, false, true),
  ('public.resolve_booking_source(text,text,text)', false, false, true),
  ('public.register_payment_webhook_event(text,text,text,text)', false, false, true),
  ('public.record_provider_payment(uuid,uuid,uuid,text,numeric,boolean,timestamptz)', false, false, true),
  ('public.record_calendar_sync_result(uuid,integer,boolean,public.calendar_provider,text,text)', false, false, true),
  ('public.claim_calendar_outbox(text,integer,integer)', false, false, true),
  ('public.record_calendar_outbox_result(uuid,text,integer,boolean,text,text)', false, false, true),
  ('public.claim_calendar_availability_outbox(text,integer,integer)', false, false, true),
  ('public.record_calendar_availability_outbox_result(uuid,text,integer,boolean,text,text)', false, false, true),
  ('public.set_calendar_connection_metadata(uuid,text,text,boolean)', false, false, true),
  ('public.authorize_calendar_actor(text,uuid)', false, false, true),
  ('public.resolve_monzo_deposit_redirect(uuid)', false, false, true),
  ('public.register_monzo_reconciliation_candidate(text,text,text,numeric,text,timestamptz)', false, false, true),
  ('public.service_resolve_gmail_target(uuid,uuid,uuid)', false, false, true),
  ('public.service_set_gmail_integration(uuid,text,text,text[])', false, false, true),
  ('public.service_disable_gmail_integration(uuid,text,text)', false, false, true),
  ('public.service_upsert_gmail_thread_context(uuid,uuid,uuid,text,text,text,text)', false, false, true),
  ('public.service_get_gmail_thread_context(uuid,uuid,uuid,uuid)', false, false, true),
  ('public.claim_email_outbox(text,integer,integer)', false, false, true),
  ('public.record_email_outbox_result(uuid,text,boolean,text,text)', false, false, true),
  ('public.list_calendar_connection_status()', false, true, false),
  ('public.record_activity(text,uuid,uuid,uuid,uuid,jsonb)', false, true, false),
  ('public.create_manual_enquiry(uuid,uuid,jsonb,jsonb,boolean)', false, true, false),
  ('public.transition_enquiry_status(uuid,public.enquiry_status)', false, true, false),
  ('public.assign_enquiry(uuid,uuid)', false, true, false),
  ('public.convert_enquiry_to_project(uuid,text,text)', false, true, false),
  ('public.schedule_session(uuid,timestamptz,timestamptz,public.session_status,text)', false, true, false),
  ('public.set_session_status(uuid,public.session_status)', false, true, false),
  ('public.list_appointment_conflicts(uuid,timestamptz,timestamptz,uuid)', false, true, false),
  ('public.schedule_appointment(uuid,uuid,public.appointment_type,timestamptz,timestamptz,public.session_status,uuid,uuid,text)', false, true, false),
  ('public.set_appointment_status(uuid,public.session_status)', false, true, false),
  ('public.reschedule_appointment(uuid,timestamptz,timestamptz)', false, true, false),
  ('public.list_artist_availability_blocks(uuid,timestamptz,timestamptz,boolean)', false, true, false),
  ('public.create_artist_availability_block(uuid,public.availability_block_kind,timestamptz,timestamptz,boolean,text)', false, true, false),
  ('public.update_artist_availability_block(uuid,public.availability_block_kind,timestamptz,timestamptz,boolean,text)', false, true, false),
  ('public.cancel_artist_availability_block(uuid)', false, true, false),
  ('public.update_project_deposit(uuid,numeric,public.deposit_status,text)', false, true, false),
  ('public.update_project_estimate(uuid,numeric,numeric,integer,numeric,text)', false, true, false),
  ('public.create_internal_note(text,uuid,uuid,uuid,uuid)', false, true, false),
  ('public.create_follow_up(text,timestamptz,uuid,uuid,uuid,uuid,text)', false, true, false),
  ('public.complete_follow_up(uuid)', false, true, false),
  ('public.create_email_draft(text,text,text,uuid,uuid,uuid,text)', false, true, false),
  ('public.approve_email_draft(uuid)', false, true, false),
  ('public.gpt_authorize_gmail_enquiry(uuid)', false, true, false),
  ('public.gpt_create_gmail_reply_draft(uuid,uuid,text)', false, true, false),
  ('public.set_profile_active(uuid,boolean)', false, true, false),
  ('public.set_profile_role(uuid,public.crm_role)', false, true, false),
  ('public.list_profiles()', false, true, false),
  ('public.list_team_memberships()', false, true, false),
  ('public.begin_staff_invite(uuid,text,text,public.crm_role,jsonb)', false, true, false),
  ('public.finalize_staff_invite(uuid)', false, true, false),
  ('public.list_assignable_profiles()', false, true, false),
  ('public.update_retention_policy(boolean,integer,integer,integer,integer,boolean)', false, true, false),
  ('public.list_accessible_artists()', false, true, false),
  ('public.update_client_details(uuid,jsonb)', false, true, false),
  ('public.update_enquiry_details(uuid,jsonb)', false, true, false),
  ('public.prepare_enquiry_reference_upload(uuid,text,text,bigint)', false, true, false),
  ('public.finalize_enquiry_reference_upload(uuid)', false, true, false),
  ('public.cancel_enquiry_reference_upload(uuid)', false, true, false),
  ('public.remove_enquiry_reference_manifest(uuid)', false, true, false),
  ('public.upsert_artist_membership(uuid,uuid,public.artist_access_level,boolean,boolean,boolean,boolean,boolean)', false, true, false),
  ('public.configure_artist_integration(uuid,public.artist_integration_type,text,text,text,jsonb,boolean)', false, true, false),
  ('public.create_artist_payment_policy(uuid,integer,public.payment_policy_mode,numeric,numeric,integer,boolean,text,timestamptz)', false, true, false),
  ('public.create_payment_request(uuid,uuid,uuid,public.payment_request_purpose,numeric,uuid,uuid,text,timestamptz)', false, true, false),
  ('public.record_manual_payment(uuid,uuid,numeric,timestamptz,text)', false, true, false),
  ('public.record_manual_refund(uuid,uuid,numeric,boolean,timestamptz,text)', false, true, false),
  ('public.cancel_payment_request(uuid)', false, true, false),
  ('public.transfer_work_to_artist(uuid,uuid,uuid,text)', false, true, false),
  ('public.configure_monzo_easy_bank_transfer(uuid,text,boolean)', false, true, false),
  ('public.get_monzo_easy_bank_transfer_settings(uuid)', false, true, false),
  ('public.request_session_deposit(uuid,uuid,text)', false, true, false),
  ('public.list_monzo_reconciliation_candidates(uuid)', false, true, false),
  ('public.match_monzo_reconciliation_candidate(uuid,uuid)', false, true, false),
  ('public.ignore_monzo_reconciliation_candidate(uuid)', false, true, false),
  ('public.confirm_monzo_reconciliation_candidate(uuid)', false, true, false),
  ('public.ensure_whatsapp_conversation_for_enquiry(uuid)', false, true, false),
  ('public.queue_whatsapp_message(uuid,text,uuid)', false, true, false),
  ('crm_private.jwt_role()', false, true, true),
  ('crm_private.is_service_backend()', false, true, true),
  ('crm_private.no_active_owner()', false, true, true);

with mismatches as (
  select *,
    has_function_privilege('anon', signature, 'EXECUTE') as actual_anon,
    has_function_privilege('authenticated', signature, 'EXECUTE') as actual_authenticated,
    has_function_privilege('service_role', signature, 'EXECUTE') as actual_service
  from expected_acl
  where has_function_privilege('anon', signature, 'EXECUTE') is distinct from anon_allowed
     or has_function_privilege('authenticated', signature, 'EXECUTE') is distinct from authenticated_allowed
     or has_function_privilege('service_role', signature, 'EXECUTE') is distinct from service_role_allowed
)
select is(
  (select count(*)::int from mismatches),
  0,
  'ACL mismatches: ' || coalesce((
    select string_agg(
      format('%s expected[%s,%s,%s] actual[%s,%s,%s]', signature, anon_allowed, authenticated_allowed, service_role_allowed, actual_anon, actual_authenticated, actual_service),
      '; ' order by signature
    ) from mismatches
  ), 'none')
);

select * from finish();
rollback;