-- 331_enquiry_v2_sql_parity.sql
-- GENERATED by scripts/test-enquiry-v2-sql-catalogue.mjs --write. Do not edit by hand.
-- Expected values come from workers/lib/enquiry-v2.js; the SQL normaliser
-- (crm_private.normalise_enquiry_project_input) must return the same.

begin;
select no_plan();

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"arm","placements":["full_sleeve","forearm"],"work":["cover_up"]},{"region":"leg","placements":["calf"],"work":["new"]}],"styles":["colour"],"sizeNotes":"  Whole left arm, calf about 15 cm  ","existingDetails":"Old tribal band on the forearm"}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Arm","placements":["Full sleeve","Forearm"],"work":["Cover-up"]},{"region":"Leg","placements":["Calf"],"work":["New tattoo"]}],"styles":["Colour realism"],"sizeNotes":"Whole left arm, calf about 15 cm","existingDetails":"Old tribal band on the forearm","imageRequirements":{"designReference":true,"existingTattooPhoto":true}},"project_type":"Cover-up","placement":"Arm: Full sleeve, Forearm; Leg: Calf","approximate_size":"Whole left arm, calf about 15 cm","cover_up":"Yes"}'::jsonb,
  'parity: full sleeve with forearm cover-up and a colour leg tattoo');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"arm","placements":["forearm"],"work":["new"]}],"styles":["black_grey"]}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Arm","placements":["Forearm"],"work":["New tattoo"]}],"styles":["Black & Grey realism"],"imageRequirements":{"designReference":true,"existingTattooPhoto":false}},"project_type":"Black and grey realism","placement":"Arm: Forearm","approximate_size":"Not specified","cover_up":"No"}'::jsonb,
  'parity: single new black and grey forearm');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"back","placements":["full_back"],"work":["rework"]}],"styles":["black_grey","colour"],"existingDetails":"Faded piece from 2015"}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Back","placements":["Full back"],"work":["Rework"]}],"styles":["Black & Grey realism","Colour realism"],"existingDetails":"Faded piece from 2015","imageRequirements":{"designReference":true,"existingTattooPhoto":true}},"project_type":"Large-scale project / sleeve","placement":"Back: Full back","approximate_size":"Not specified","cover_up":"Existing tattoo"}'::jsonb,
  'parity: full back rework in both styles');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"other","placements":[],"otherPlacement":"Inner lip","work":["new"]}],"styles":["not_sure"],"existingDetails":"ignored because nothing existing"}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Other","placements":[],"otherPlacement":"Inner lip","work":["New tattoo"]}],"styles":["Not sure yet"],"imageRequirements":{"designReference":true,"existingTattooPhoto":false}},"project_type":"Not sure yet","placement":"Other: Inner lip","approximate_size":"Not specified","cover_up":"No"}'::jsonb,
  'parity: other region, not sure of style, existing details dropped for new work');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"arm","placements":["other"],"otherPlacement":"Back of the arm","work":["extension"]},{"region":"hand","placements":["fingers"],"work":["new"]}],"styles":["colour","black_grey"]}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Arm","placements":["Other"],"otherPlacement":"Back of the arm","work":["Extension"]},{"region":"Hand","placements":["Fingers"],"work":["New tattoo"]}],"styles":["Colour realism","Black & Grey realism"],"imageRequirements":{"designReference":true,"existingTattooPhoto":true}},"project_type":"Colour and black and grey realism","placement":"Arm: Back of the arm; Hand: Fingers","approximate_size":"Not specified","cover_up":"Existing tattoo"}'::jsonb,
  'parity: other arm placement extension plus new fingers');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"chest_ribs","placements":["ribs","collarbone"],"work":["extension","rework"]}],"styles":["colour"],"sizeNotes":"Palm\u0007 sized"}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Chest & Ribs","placements":["Ribs","Collarbone"],"work":["Extension","Rework"]}],"styles":["Colour realism"],"sizeNotes":"Palm sized","imageRequirements":{"designReference":true,"existingTattooPhoto":true}},"project_type":"Colour realism","placement":"Chest & Ribs: Ribs, Collarbone","approximate_size":"Palm sized","cover_up":"Existing tattoo"}'::jsonb,
  'parity: ribs extension and rework, colour');

select is(crm_private.normalise_enquiry_project_input('{"areas":[{"region":"leg","placements":["half_leg_sleeve","knee"],"work":["new"]}],"styles":["black_grey"]}'::jsonb),
  '{"project_details":{"schema":"enquiry-v2","areas":[{"region":"Leg","placements":["Half leg sleeve","Knee"],"work":["New tattoo"]}],"styles":["Black & Grey realism"],"imageRequirements":{"designReference":true,"existingTattooPhoto":false}},"project_type":"Large-scale project / sleeve","placement":"Leg: Half leg sleeve, Knee","approximate_size":"Not specified","cover_up":"No"}'::jsonb,
  'parity: half leg sleeve new');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"tail","placements":[],"work":["new"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject unknown region');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["half_sleeve","full_sleeve"],"work":["new"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject two sleeve lengths');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["forearm"],"work":["new","cover_up"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject new combined with cover-up');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["forearm"],"work":[]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject no work');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":[],"work":["new"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject no placement');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"other","placements":[],"work":["new"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject other without text');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["forearm"],"work":["new"]}],"styles":[]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject no style');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["forearm"],"work":["new"]}],"styles":["not_sure","colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject not sure with another style');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[{"region":"arm","placements":["forearm"],"work":["new"]},{"region":"arm","placements":["wrist"],"work":["new"]}],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject repeated region');

select throws_ok('select crm_private.normalise_enquiry_project_input(''{"areas":[],"styles":["colour"]}''::jsonb)',
  '22023', null, 'parity: Worker and SQL both reject no areas');

select * from finish(true);
rollback;
