import type { Language } from './i18n';
import type { OutboxJob } from './types';

export type OperationalLabelGroup = 'event' | 'integrationKind' | 'integrationError';

export const ACTIVITY_EVENT_TYPES = [
  'attention.dismissed',
  'appointment.rescheduled',
  'appointment.scheduled',
  'appointment.status_changed',
  'artist.work_transferred',
  'client.created',
  'enquiry.assigned',
  'enquiry.converted',
  'enquiry.created',
  'enquiry.intake_completed',
  'enquiry.reviewed',
  'enquiry.source_resolved',
  'enquiry.status_changed',
  'finance.updated',
  'follow_up.completed',
  'follow_up.created',
  'integration.configured',
  'integration.google_contacts_disabled',
  'integration.google_contacts_enabled',
  'integration.queued',
  'membership.updated',
  'note.created',
  'outbox.failed',
  'outbox.succeeded',
  'owner.bootstrapped',
  'payment.manual_recorded',
  'payment.recorded',
  'payment.reconciliation_confirmed',
  'payment.reconciliation_ignored',
  'payment.reconciliation_matched',
  'payment.request_cancelled',
  'payment.request_created',
  'profile.activated',
  'profile.deactivated',
  'profile.invite_requested',
  'profile.provisioned',
  'profile.role_changed',
  'profile.updated',
  'project.deposit_changed',
  'project.deposit_updated',
  'project.estimate_updated',
  'project.reviewed',
  'project.status_changed',
  'session.created',
  'session.scheduled',
  'session.status_changed',
] as const;

const LABELS: Record<Language, Record<OperationalLabelGroup, Record<string, string>>> = {
  en: {
    event: {
      'client_ai.state_refreshed': 'AI brief updated',
      'client_ai.image_analyzed': 'Reference image analysed',
      'enquiry.ai_completed': 'Enquiry AI summary ready',
      'enquiry.ai_failed': 'Enquiry AI summary failed',
      'outbox.created': 'Integration job queued',
      'appointment.ai_scheduled': 'Appointment scheduled by the assistant',
      'appointment.ai_rescheduled': 'Appointment moved by the assistant',
      'booking_source.created': 'Booking source added',
      'booking_source.updated': 'Booking source updated',
      'signup.tenant_created': 'Account created',
      'signup.availability_changed': 'Sign-up availability changed',
      'invite.tenant_availability_changed': 'Invitation availability changed',
      'whatsapp.conversation_created': 'WhatsApp conversation started',
      'whatsapp.queued': 'WhatsApp message queued',
      'instagram.connected': 'Instagram connected',
      'integration.calendar_connected': 'Calendar connected',
      'enquiry.reference_uploaded': 'Reference uploaded',
      'enquiry.reference_upload_prepared': 'Reference upload prepared',
      'enquiry.manual_created': 'Manual enquiry created',
      'enquiry.updated': 'Enquiry updated',
      'enquiry.archived': 'Enquiry archived',
      'communication.state_changed': 'Conversation state changed',
      'communication.not_crm_marked': 'Conversation marked personal',
      'communication.not_crm_cleared': 'Personal mark removed',
      'client.phone_country_normalized': 'Client phone put in international form',
      'client.updated': 'Client updated',
      'client.archived': 'Client archived',
      'automation.template_created': 'Message template created',
      'automation.template_updated': 'Message template updated',
      'workspace.created': 'Organization created',
      'workspace.membership_changed': 'Organization access changed',
      'outbox.telegram_auto_recovered': 'Telegram delivery recovered automatically',
      'payment.project_deposit_policy_configured': 'Deposit rule configured',
      'payment.project_deposit_requested': 'Project deposit requested',
      'project.deposit_override_set': 'Project deposit changed manually',
      'email.draft_created': 'Email draft created',
      'email.approved': 'Email approved',
      'account.self_deleted': 'Account deleted by its owner',
      'gpt.client_configured': 'Assistant connection configured',
      'settings.retention_updated': 'Data retention settings updated',
      'attention.dismissed': 'Attention item removed',
      'attention.restored': 'Attention item returned',
      'appointment.rescheduled': 'Appointment rescheduled',
      'appointment.scheduled': 'Appointment scheduled',
      'appointment.status_changed': 'Appointment status changed',
      'artist.work_transferred': 'Artist work transferred',
      'client.created': 'Client created',
      'enquiry.assigned': 'Enquiry assigned',
      'enquiry.converted': 'Enquiry converted to project',
      'enquiry.created': 'Enquiry created',
      'enquiry.intake_completed': 'Enquiry intake completed',
      'enquiry.reviewed': 'Enquiry reviewed',
      'enquiry.source_resolved': 'Enquiry source resolved',
      'enquiry.status_changed': 'Enquiry status changed',
      'finance.updated': 'Project estimate updated',
      'follow_up.completed': 'Follow-up completed',
      'follow_up.created': 'Follow-up created',
      'integration.configured': 'Integration configured',
      'integration.google_contacts_disabled': 'Google Contacts sync disabled',
      'integration.google_contacts_enabled': 'Google Contacts sync enabled',
      'integration.queued': 'Integration queued',
      'membership.updated': 'Artist access updated',
      'note.created': 'Internal note added',
      'outbox.failed': 'Integration sync failed',
      'outbox.succeeded': 'Integration sync completed',
      'owner.bootstrapped': 'Owner access created',
      'payment.manual_recorded': 'Manual payment recorded',
      'payment.recorded': 'Payment recorded',
      'payment.reconciliation_confirmed': 'Monzo payment confirmed',
      'payment.reconciliation_ignored': 'Monzo transfer ignored',
      'payment.reconciliation_matched': 'Monzo transfer matched',
      'payment.request_cancelled': 'Payment request cancelled',
      'payment.request_created': 'Payment request created',
      'profile.activated': 'User activated',
      'profile.deactivated': 'User deactivated',
      'profile.invite_requested': 'Staff invitation requested',
      'profile.provisioned': 'Staff access provisioned',
      'profile.role_changed': 'User role changed',
      'profile.updated': 'User profile updated',
      'project.deposit_changed': 'Project deposit status changed',
      'project.deposit_updated': 'Project deposit updated',
      'project.estimate_updated': 'Project estimate updated',
      'project.reviewed': 'Project reviewed',
      'project.status_changed': 'Project status changed',
      'session.created': 'Session created',
      'session.scheduled': 'Session scheduled',
      'session.status_changed': 'Session status changed',
    },
    integrationKind: {
      approved_email: 'Approved email',
      whatsapp_message: 'WhatsApp message',
      calendar_availability_create: 'Calendar block created',
      calendar_availability_update: 'Calendar block updated',
      calendar_create: 'Create calendar event',
      calendar_update: 'Update calendar event',
      calendar_cancel: 'Cancel calendar event',
      google_contact_create: 'Save Google contact',
      telegram_notification: 'Telegram notification',
    },
    integrationError: {
      database_unavailable: 'Database temporarily unavailable',
      operator_cancelled: 'Cancelled by an operator',
      gmail_deposit_email_obsolete: 'Deposit email no longer needed',
      gmail_rpc_failed: 'Gmail request failed',
      artist_route_unconfigured: 'Artist calendar route is not configured',
      calendar_connector_error: 'Calendar connector failed',
      calendar_encryption_key_invalid: 'Calendar token encryption is misconfigured',
      calendar_event_missing: 'Calendar event reference is missing',
      calendar_job_invalid: 'Calendar job is invalid',
      calendar_not_configured: 'Calendar is not configured',
      calendar_oauth_expired: 'Calendar connection has expired',
      calendar_provider_rejected: 'Calendar provider rejected the request',
      calendar_provider_unavailable: 'Calendar provider is temporarily unavailable',
      calendar_scope_missing: 'Calendar permission is missing',
      calendar_token_invalid: 'Stored Calendar connection is invalid',
      google_account_mismatch: 'The connected Google account does not match this artist',
      google_contact_job_invalid: 'Google contact job is invalid',
      google_contacts_connector_error: 'Google Contacts connector failed',
      google_contacts_create_result_unknown: 'Google Contacts create result is uncertain and will be checked again',
      google_contacts_metadata_update_failed: 'Google Contacts connection metadata could not be updated',
      google_contacts_not_enabled: 'Google Contacts sync is not enabled',
      google_contacts_permission_denied: 'Google Contacts permission was denied',
      google_contacts_provider_rejected: 'Google Contacts rejected the request',
      google_contacts_provider_unavailable: 'Google Contacts is temporarily unavailable',
      google_contacts_scope_missing: 'Google Contacts permission is missing; reconnect Google',
      google_rate_limited: 'Google Calendar rate limit reached',
      google_refresh_invalid_grant: 'Google Calendar access grant is invalid',
      google_token_revoked: 'Google Calendar access was revoked',
      provider_route_invalid: 'Calendar provider route is invalid',
      provider_route_unavailable: 'Provider route unavailable',
      telegram_rejected: 'Telegram rejected the request',
    },
  },
  ru: {
    event: {
      'client_ai.state_refreshed': 'AI-бриф обновлён',
      'client_ai.image_analyzed': 'Референс проанализирован',
      'enquiry.ai_completed': 'AI-сводка по заявке готова',
      'enquiry.ai_failed': 'Не удалось подготовить AI-сводку по заявке',
      'outbox.created': 'Задача интеграции поставлена в очередь',
      'appointment.ai_scheduled': 'Запись создана ассистентом',
      'appointment.ai_rescheduled': 'Запись перенесена ассистентом',
      'booking_source.created': 'Источник заявок добавлен',
      'booking_source.updated': 'Источник заявок изменён',
      'signup.tenant_created': 'Аккаунт создан',
      'signup.availability_changed': 'Доступность регистрации изменена',
      'invite.tenant_availability_changed': 'Доступность приглашений изменена',
      'whatsapp.conversation_created': 'Начата переписка в WhatsApp',
      'whatsapp.queued': 'Сообщение WhatsApp в очереди',
      'instagram.connected': 'Instagram подключён',
      'integration.calendar_connected': 'Календарь подключён',
      'enquiry.reference_uploaded': 'Референс загружен',
      'enquiry.reference_upload_prepared': 'Загрузка референса подготовлена',
      'enquiry.manual_created': 'Заявка создана вручную',
      'enquiry.updated': 'Заявка изменена',
      'enquiry.archived': 'Заявка в архиве',
      'communication.state_changed': 'Статус переписки изменён',
      'communication.not_crm_marked': 'Переписка отмечена как личная',
      'communication.not_crm_cleared': 'Отметка «личное» снята',
      'client.phone_country_normalized': 'Телефон клиента приведён к международному формату',
      'client.updated': 'Клиент изменён',
      'client.archived': 'Клиент в архиве',
      'automation.template_created': 'Шаблон сообщения создан',
      'automation.template_updated': 'Шаблон сообщения изменён',
      'workspace.created': 'Организация создана',
      'workspace.membership_changed': 'Доступ в организации изменён',
      'outbox.telegram_auto_recovered': 'Доставка в Telegram восстановлена автоматически',
      'payment.project_deposit_policy_configured': 'Правило депозита настроено',
      'payment.project_deposit_requested': 'Запрошен депозит по проекту',
      'project.deposit_override_set': 'Депозит по проекту изменён вручную',
      'email.draft_created': 'Черновик письма создан',
      'email.approved': 'Письмо одобрено',
      'account.self_deleted': 'Аккаунт удалён владельцем',
      'gpt.client_configured': 'Подключение ассистента настроено',
      'settings.retention_updated': 'Настройки хранения данных изменены',
      'attention.dismissed': 'Карточка убрана из внимания',
      'attention.restored': 'Карточка возвращена во внимание',
      'appointment.rescheduled': 'Запись перенесена',
      'appointment.scheduled': 'Запись запланирована',
      'appointment.status_changed': 'Статус записи изменён',
      'artist.work_transferred': 'Работа передана другому мастеру',
      'client.created': 'Клиент создан',
      'enquiry.assigned': 'Назначен исполнитель',
      'enquiry.converted': 'Заявка преобразована в проект',
      'enquiry.created': 'Заявка создана',
      'enquiry.intake_completed': 'Приём заявки завершён',
      'enquiry.reviewed': 'Заявка проверена',
      'enquiry.source_resolved': 'Источник заявки определён',
      'enquiry.status_changed': 'Статус заявки изменён',
      'finance.updated': 'Расчёт проекта обновлён',
      'follow_up.completed': 'Напоминание выполнено',
      'follow_up.created': 'Напоминание создано',
      'integration.configured': 'Интеграция настроена',
      'integration.google_contacts_disabled': 'Синхронизация Google Contacts отключена',
      'integration.google_contacts_enabled': 'Синхронизация Google Contacts включена',
      'integration.queued': 'Синхронизация поставлена в очередь',
      'membership.updated': 'Доступ к мастеру обновлён',
      'note.created': 'Добавлена внутренняя заметка',
      'outbox.failed': 'Ошибка синхронизации интеграции',
      'outbox.succeeded': 'Синхронизация интеграции выполнена',
      'owner.bootstrapped': 'Доступ владельца создан',
      'payment.manual_recorded': 'Ручная оплата зафиксирована',
      'payment.recorded': 'Платёж зарегистрирован',
      'payment.reconciliation_confirmed': 'Оплата Monzo подтверждена',
      'payment.reconciliation_ignored': 'Перевод Monzo проигнорирован',
      'payment.reconciliation_matched': 'Перевод Monzo сопоставлен',
      'payment.request_cancelled': 'Платёжный запрос отменён',
      'payment.request_created': 'Платёжный запрос создан',
      'profile.activated': 'Пользователь активирован',
      'profile.deactivated': 'Пользователь деактивирован',
      'profile.invite_requested': 'Запрошено приглашение сотрудника',
      'profile.provisioned': 'Доступ сотрудника подготовлен',
      'profile.role_changed': 'Роль пользователя изменена',
      'profile.updated': 'Профиль пользователя обновлён',
      'project.deposit_changed': 'Статус депозита проекта изменён',
      'project.deposit_updated': 'Депозит проекта обновлён',
      'project.estimate_updated': 'Расчёт проекта обновлён',
      'project.reviewed': 'Проект проверен',
      'project.status_changed': 'Статус проекта изменён',
      'session.created': 'Сеанс создан',
      'session.scheduled': 'Сеанс запланирован',
      'session.status_changed': 'Статус сеанса изменён',
    },
    integrationKind: {
      approved_email: 'Одобренное письмо',
      whatsapp_message: 'Сообщение WhatsApp',
      calendar_availability_create: 'Блокировка в календаре создана',
      calendar_availability_update: 'Блокировка в календаре изменена',
      calendar_create: 'Создание события календаря',
      calendar_update: 'Обновление события календаря',
      calendar_cancel: 'Отмена события календаря',
      google_contact_create: 'Сохранение контакта Google',
      telegram_notification: 'Telegram-уведомление',
    },
    integrationError: {
      database_unavailable: 'База данных временно недоступна',
      operator_cancelled: 'Отменено оператором',
      gmail_deposit_email_obsolete: 'Письмо о депозите больше не нужно',
      gmail_rpc_failed: 'Запрос к Gmail не выполнен',
      artist_route_unconfigured: 'Маршрут календаря мастера не настроен',
      calendar_connector_error: 'Ошибка Calendar connector',
      calendar_encryption_key_invalid: 'Неверно настроено шифрование токена календаря',
      calendar_event_missing: 'Отсутствует ссылка на событие календаря',
      calendar_job_invalid: 'Некорректная задача календаря',
      calendar_not_configured: 'Календарь не настроен',
      calendar_oauth_expired: 'Подключение календаря истекло',
      calendar_provider_rejected: 'Календарь отклонил запрос',
      calendar_provider_unavailable: 'Календарь временно недоступен',
      calendar_scope_missing: 'Отсутствует разрешение на работу с календарём',
      calendar_token_invalid: 'Сохранённое подключение календаря повреждено',
      google_account_mismatch: 'Подключённый Google-аккаунт не соответствует мастеру',
      google_contact_job_invalid: 'Некорректная задача Google Contacts',
      google_contacts_connector_error: 'Ошибка Google Contacts connector',
      google_contacts_create_result_unknown: 'Результат создания контакта неизвестен, CRM проверит его повторно',
      google_contacts_metadata_update_failed: 'Не удалось обновить метаданные Google Contacts',
      google_contacts_not_enabled: 'Синхронизация Google Contacts не включена',
      google_contacts_permission_denied: 'Нет разрешения Google Contacts',
      google_contacts_provider_rejected: 'Google Contacts отклонил запрос',
      google_contacts_provider_unavailable: 'Google Contacts временно недоступен',
      google_contacts_scope_missing: 'Нет разрешения Google Contacts, переподключи Google',
      google_rate_limited: 'Превышен лимит запросов Google Calendar',
      google_refresh_invalid_grant: 'Разрешение Google Calendar недействительно',
      google_token_revoked: 'Доступ Google Calendar отозван',
      provider_route_invalid: 'Некорректный маршрут Calendar provider',
      provider_route_unavailable: 'Маршрут интеграции недоступен',
      telegram_rejected: 'Telegram отклонил запрос',
    },
  },
};

function humanise(value: string): string {
  const text = value.replace(/[._]/g, ' ').replace(/\s+/g, ' ').trim();
  return text ? `${text.charAt(0).toUpperCase()}${text.slice(1)}` : '—';
}

export function operationalLabel(
  language: Language,
  group: OperationalLabelGroup,
  value: string | null | undefined
): string {
  if (!value) return '—';
  return LABELS[language][group][value] ?? LABELS.en[group][value] ?? humanise(value);
}

export interface FailedJobGroup {
  key: string;
  kind: string;
  status: OutboxJob['status'];
  errorCode: string | null;
  count: number;
  latestJob: OutboxJob;
}

export function groupFailedJobs(jobs: OutboxJob[]): FailedJobGroup[] {
  const groups = new Map<string, FailedJobGroup>();

  for (const job of jobs) {
    const key = `${job.kind}\u0000${job.last_error_code ?? job.status}`;
    const existing = groups.get(key);

    if (!existing) {
      groups.set(key, {
        key,
        kind: job.kind,
        status: job.status,
        errorCode: job.last_error_code,
        count: 1,
        latestJob: job,
      });
      continue;
    }

    existing.count += 1;
    if (new Date(job.updated_at).getTime() > new Date(existing.latestJob.updated_at).getTime()) {
      existing.latestJob = job;
    }
  }

  return Array.from(groups.values()).sort(
    (left, right) => new Date(right.latestJob.updated_at).getTime() - new Date(left.latestJob.updated_at).getTime()
  );
}
