-- 0096_client_lifecycle_scheduling_integrity.sql
--
-- Two corrections to the lifecycle work introduced by 0093, found reviewing the
-- scheduler rather than by a failing test. Production is still at 0091, so like
-- 0095 this is a forward-only correction inside the same unreleased rollout
-- rather than an edit to an already-published migration file.
--
-- 1. Materialisation could starve itself
-- --------------------------------------
-- The batch selected candidate (rule, event) pairs and only then discarded the
-- ones that resolve to no schedule. A client rule is conditioned on exactly one
-- appointment type, but it still sees every session event its artist emits, and
-- a pair it can never match never produces a job - so `not exists (job)` stays
-- true for it forever and it is selected again on every tick.
--
-- Ordering is by `occurred_at`, so those permanent residents sort to the front.
-- Once an artist has accumulated more of them than the tick limit, they occupy
-- the entire batch and every reminder behind them stops being scheduled. The
-- automation goes quiet with no error anywhere, which is the worst shape this
-- failure could take.
--
-- The appointment-type match therefore has to be a predicate on the batch, not
-- a filter applied after it. The `scheduled_at is not null` guard stays as the
-- backstop for the remaining reasons a schedule may not resolve (a session that
-- has since been deleted, an event that carries no entity id).
--
-- 2. System approval was not tied to the job that earned it
-- ---------------------------------------------------------
-- 0093 relaxed `email_messages_approval_required` so a lifecycle message can be
-- approved with no human approver. That is correct - there is no human author
-- to name - but the constraint granted it to any row merely claiming
-- `created_by_kind = 'system'`, and only the trigger tied that provenance to a
-- real lifecycle job.
--
-- No API role can write `public.email_messages` today (`authenticated` holds
-- SELECT and nothing else) and `create_email_draft` rejects any kind outside
-- human/ai, so the branch is unreachable in this release. It is still the wrong
-- invariant to leave written down: a constraint is checked whoever writes the
-- row, and the next insert path should not be able to reach the no-approver
-- branch by accident. Requiring `automation_job_id` states the real rule.
--
-- Forward-only. No rule is enabled, no template activated, no provider
-- contacted, and no row is rewritten.

-- ---------------------------------------------------------------------------
-- 1. Approval provenance
-- ---------------------------------------------------------------------------

alter table public.email_messages
  drop constraint if exists email_messages_approval_required;
alter table public.email_messages
  add constraint email_messages_approval_required
  check (
    status not in ('approved', 'queued', 'sent')
    or (
      approved_at is not null
      and (
        (created_by_kind = 'system'
           and approved_by is null
           and automation_job_id is not null)
        or (created_by_kind in ('human', 'ai') and approved_by is not null)
      )
    )
  );

comment on constraint email_messages_approval_required on public.email_messages is
  'Approved mail is either human-approved or system-generated by a named lifecycle job. System provenance is not a general exemption from having an approver.';

-- ---------------------------------------------------------------------------
-- 2. Materialisation selects only work that can actually be scheduled
-- ---------------------------------------------------------------------------

create or replace function public.service_run_automation_tick(p_limit integer default 100)
returns table (
  materialised integer,
  withdrawn    integer,
  executed     integer,
  notified     integer
)
language plpgsql
security definer
set search_path = pg_catalog, public, crm_private
as $$
declare
  v_materialised integer := 0;
  v_withdrawn integer := 0;
  v_executed integer := 0;
  v_notified integer := 0;
  v_client_job record;
  v_client_result text;
begin
  if not crm_private.is_service_backend() then
    raise exception 'automation ticks are backend-only' using errcode = '42501';
  end if;

  if p_limit is null or p_limit < 1 or p_limit > 500 then
    raise exception 'automation tick limit must be between 1 and 500' using errcode = '22023';
  end if;

  with pairs as (
    select r.id as rule_id, r.version, e.id as event_id, e.artist_id,
           r.action_type, r.action_title, r.action_body, r.action_priority,
           r.schedule_anchor, r.anchor_offset_minutes,
           r.condition_appointment_type,
           r.message_purpose, r.message_channel, r.message_locale,
           case
             when r.action_type = 'send_client_message'::public.automation_action_type
             then e.entity_id
             else null
           end as session_id,
           crm_private.resolve_automation_scheduled_at(
             r.schedule_anchor,
             r.delay_minutes,
             r.anchor_offset_minutes,
             e.occurred_at,
             e.artist_id,
             e.entity_kind,
             e.entity_id,
             r.condition_appointment_type
           ) as scheduled_at
    from public.automation_events e
    join public.automation_rules r
      on r.artist_id = e.artist_id
     and r.trigger_event_type = e.event_type
     and r.is_enabled
    where (r.condition_from_status is null or r.condition_from_status = e.from_status)
      and (r.condition_to_status is null or r.condition_to_status = e.to_status)
      and not exists (
        select 1 from public.automation_jobs j
        where j.rule_id = r.id and j.event_id = e.id
      )
      -- A client rule conditioned on one appointment type still sees every
      -- session event its artist emits, and an event it can never match never
      -- produces a job. Without this predicate those pairs are re-selected on
      -- every tick, and once there are more of them than p_limit they occupy
      -- the whole batch in occurred_at order and starve the real work behind
      -- them. Excluding them here rather than after the limit is what keeps
      -- the batch made of pairs that can actually materialise.
      and (
        r.action_type <> 'send_client_message'::public.automation_action_type
        or exists (
          select 1
          from public.sessions s
          where s.id = e.entity_id
            and s.artist_id = e.artist_id
            and s.appointment_type = r.condition_appointment_type
        )
      )
    order by e.occurred_at, e.id
    limit p_limit
  ),
  inserted as (
    insert into public.automation_jobs (
      rule_id, rule_version, event_id, artist_id,
      action_type, action_title, action_body, action_priority,
      schedule_anchor, anchor_offset_minutes, condition_appointment_type,
      message_purpose, message_channel, message_locale,
      session_id, scheduled_at
    )
    select rule_id, version, event_id, artist_id,
           action_type, action_title, action_body, action_priority,
           schedule_anchor, anchor_offset_minutes, condition_appointment_type,
           message_purpose, message_channel, message_locale,
           session_id, scheduled_at
    from pairs
    where scheduled_at is not null
    on conflict do nothing
    returning 1
  )
  select count(*)::int into v_materialised from inserted;

  -- Withdraw stale rule snapshots first. A later reschedule never revives work
  -- that was explicitly disabled or edited.
  with stale as (
    update public.automation_jobs j
    set status = 'cancelled',
        cancelled_at = now(),
        last_error_category = 'rule_withdrawn'
    from public.automation_rules r
    where j.rule_id = r.id
      and j.status = 'pending'
      and (not r.is_enabled or r.version <> j.rule_version)
    returning 1
  )
  select count(*)::int into v_withdrawn from stale;

  -- Reconcile every still-pending lifecycle job from the authoritative session.
  -- This is the reschedule primitive: the domain row moves, the job follows.
  update public.automation_jobs j
  set scheduled_at = case j.schedule_anchor
        when 'session_start'::public.automation_schedule_anchor
          then s.start_at + make_interval(mins => j.anchor_offset_minutes)
        when 'session_end'::public.automation_schedule_anchor
          then s.end_at + make_interval(mins => j.anchor_offset_minutes)
        else j.scheduled_at
      end
  from public.sessions s
  where j.status = 'pending'
    and j.action_type = 'send_client_message'::public.automation_action_type
    and s.id = j.session_id
    and s.artist_id = j.artist_id
    and j.scheduled_at is distinct from case j.schedule_anchor
        when 'session_start'::public.automation_schedule_anchor
          then s.start_at + make_interval(mins => j.anchor_offset_minutes)
        when 'session_end'::public.automation_schedule_anchor
          then s.end_at + make_interval(mins => j.anchor_offset_minutes)
        else j.scheduled_at
      end;

  -- Definitive appointment states cancel pending lifecycle work. Proposed/draft
  -- are deliberately not terminal: a later confirmation may still make a due
  -- reminder eligible, and the next tick will pick it up.
  update public.automation_jobs j
  set status = 'cancelled', cancelled_at = now(),
      last_error_category = 'appointment_ineligible'
  where j.status = 'pending'
    and j.action_type = 'send_client_message'::public.automation_action_type
    and (
      not exists (
        select 1 from public.sessions s
        where s.id = j.session_id
          and s.artist_id = j.artist_id
          and s.appointment_type = j.condition_appointment_type
      )
      or exists (
        select 1 from public.sessions s
        where s.id = j.session_id
          and s.artist_id = j.artist_id
          and (
            (j.schedule_anchor = 'session_start'::public.automation_schedule_anchor
             and s.status in ('cancelled', 'no_show', 'completed'))
            or
            (j.schedule_anchor = 'session_end'::public.automation_schedule_anchor
             and s.status in ('cancelled', 'no_show'))
          )
      )
    );

  -- Legacy artist-team notification execution is unchanged.
  with due as (
    select j.id, j.artist_id, j.action_title, j.action_body, j.action_priority,
           e.entity_kind, e.entity_id
    from public.automation_jobs j
    join public.automation_events e on e.id = j.event_id
    join crm_private.artist_state s on s.artist_id = j.artist_id and s.is_active
    where j.status = 'pending'
      and j.scheduled_at <= now()
      and j.action_type = 'notify_artist_team'
      and crm_private.automations_enabled_for_artist(j.artist_id)
    order by j.scheduled_at, j.id
    limit p_limit
  ),
  targeted as (
    select d.*, r.profile_id
    from due d
    cross join lateral crm_private.automation_notification_recipients(d.artist_id) r
  ),
  sent as (
    insert into public.notifications (
      recipient_profile_id, artist_id, notification_type, title, body,
      entity_type, entity_id, priority, status, dedupe_key,
      scheduled_at, delivered_at
    )
    select t.profile_id, t.artist_id, 'automation.triggered',
           t.action_title, t.action_body,
           case when t.entity_id is not null then t.entity_kind end,
           t.entity_id, t.action_priority,
           'delivered',
           'automation_job:' || t.id::text || ':' || t.profile_id::text,
           now(), now()
    from targeted t
    on conflict (dedupe_key) do nothing
    returning 1
  ),
  finished as (
    update public.automation_jobs j
    set status = 'completed',
        completed_at = now(),
        attempt_count = j.attempt_count + 1,
        last_error_category = case
          when exists (select 1 from targeted t where t.id = j.id) then 'none'
          else 'no_recipient'
        end
    where j.id in (select id from due)
    returning 1
  )
  select (select count(*)::int from finished), (select count(*)::int from sent)
  into v_executed, v_notified;

  -- Client work is executed one locked job at a time. The helper rechecks every
  -- live gate under that lock and creates email + outbox atomically.
  for v_client_job in
    select j.id
    from public.automation_jobs j
    join public.sessions s
      on s.id = j.session_id
     and s.artist_id = j.artist_id
    join crm_private.artist_state a
      on a.artist_id = j.artist_id
     and a.is_active
    where j.status = 'pending'
      and j.action_type = 'send_client_message'::public.automation_action_type
      and j.scheduled_at <= now()
      and crm_private.automations_enabled_for_artist(j.artist_id)
      and (
        (j.schedule_anchor = 'session_start'::public.automation_schedule_anchor
         and s.status = 'confirmed')
        or
        (j.schedule_anchor = 'session_end'::public.automation_schedule_anchor
         and s.status = 'completed')
      )
    order by j.scheduled_at, j.id
    limit p_limit
  loop
    v_client_result := crm_private.execute_client_lifecycle_job(v_client_job.id);
    if v_client_result in ('queued', 'failed', 'blocked', 'cancelled') then
      v_executed := v_executed + 1;
    end if;
  end loop;

  return query select v_materialised, v_withdrawn, v_executed, v_notified;
end;
$$;

comment on function public.service_run_automation_tick(integer) is
  'Materialises, reconciles, withdraws and executes artist-team and client-lifecycle automation. Materialisation selects only pairs that can resolve a schedule, so an event a rule can never match cannot occupy the batch. Client lifecycle schedules are re-derived from the live session and provider delivery remains in the approved-email outbox.';

-- CREATE OR REPLACE preserves privileges, but restate the backend-only grant so
-- the boundary is visible in the migration that last touched the function.
revoke all on function public.service_run_automation_tick(integer)
  from public, anon, authenticated, service_role;
grant execute on function public.service_run_automation_tick(integer) to service_role;
